// <auto-generated />
using System;
using BlogPlatformApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPlatformApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260805140455_FixComments")]
    partial class FixComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlogPlatformApi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("JoineDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sarah.j@example.com",
                            FullName = "Sarah Johnson",
                            JoineDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "m.chen@example.com",
                            FullName = "Michael Chen",
                            JoineDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Email = "emma.w@example.com",
                            FullName = "Emma Williams",
                            JoineDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.m@example.com",
                            FullName = "David Martinez",
                            JoineDate = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "lisa.a@example.com",
                            FullName = "Lisa Anderson",
                            JoineDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommenterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommenterName = "John Doe",
                            CreatedAt = new DateTime(2024, 1, 11, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Text = "Great introduction! Very helpful for beginners."
                        },
                        new
                        {
                            Id = 2,
                            CommenterName = "Jane Smith",
                            CreatedAt = new DateTime(2024, 1, 11, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Text = "Could you cover middleware in the next post?"
                        },
                        new
                        {
                            Id = 3,
                            CommenterName = "Bob Wilson",
                            CreatedAt = new DateTime(2024, 1, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Text = "This helped me get started with my first project!"
                        },
                        new
                        {
                            Id = 4,
                            CommenterName = "Alice Brown",
                            CreatedAt = new DateTime(2024, 1, 13, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Text = "Clear explanations, thank you!"
                        },
                        new
                        {
                            Id = 5,
                            CommenterName = "Charlie Davis",
                            CreatedAt = new DateTime(2024, 1, 14, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 1,
                            Text = "Looking forward to more ASP.NET content."
                        },
                        new
                        {
                            Id = 6,
                            CommenterName = "Emily White",
                            CreatedAt = new DateTime(2024, 2, 6, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Text = "EF Core migrations can be tricky, thanks for this!"
                        },
                        new
                        {
                            Id = 7,
                            CommenterName = "Frank Miller",
                            CreatedAt = new DateTime(2024, 2, 7, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Text = "What about many-to-many relationships?"
                        },
                        new
                        {
                            Id = 8,
                            CommenterName = "Grace Lee",
                            CreatedAt = new DateTime(2024, 2, 8, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Text = "Very detailed explanation of relationships."
                        },
                        new
                        {
                            Id = 9,
                            CommenterName = "Henry Taylor",
                            CreatedAt = new DateTime(2024, 2, 9, 15, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 2,
                            Text = "This solved my foreign key issues!"
                        },
                        new
                        {
                            Id = 10,
                            CommenterName = "Ivy Chen",
                            CreatedAt = new DateTime(2024, 3, 13, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            Text = "REST principles explained perfectly."
                        },
                        new
                        {
                            Id = 11,
                            CommenterName = "Jack Robinson",
                            CreatedAt = new DateTime(2024, 3, 14, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            Text = "How do you handle versioning?"
                        },
                        new
                        {
                            Id = 12,
                            CommenterName = "Kelly Martinez",
                            CreatedAt = new DateTime(2024, 3, 15, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 3,
                            Text = "Bookmarked for future reference!"
                        },
                        new
                        {
                            Id = 13,
                            CommenterName = "Leo Garcia",
                            CreatedAt = new DateTime(2024, 4, 21, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            Text = "Async/await finally makes sense!"
                        },
                        new
                        {
                            Id = 14,
                            CommenterName = "Mia Anderson",
                            CreatedAt = new DateTime(2024, 4, 22, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            Text = "Great examples of common pitfalls."
                        },
                        new
                        {
                            Id = 15,
                            CommenterName = "Noah Thomas",
                            CreatedAt = new DateTime(2024, 4, 23, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            Text = "Could you cover Task.WhenAll?"
                        },
                        new
                        {
                            Id = 16,
                            CommenterName = "Olivia Jackson",
                            CreatedAt = new DateTime(2024, 4, 24, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 4,
                            Text = "This improved my app's performance significantly."
                        },
                        new
                        {
                            Id = 17,
                            CommenterName = "Paul Harris",
                            CreatedAt = new DateTime(2024, 5, 9, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            Text = "DI was confusing until I read this."
                        },
                        new
                        {
                            Id = 18,
                            CommenterName = "Quinn Martin",
                            CreatedAt = new DateTime(2024, 5, 10, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            Text = "Service lifetimes explained clearly!"
                        },
                        new
                        {
                            Id = 19,
                            CommenterName = "Rachel Thompson",
                            CreatedAt = new DateTime(2024, 5, 11, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 5,
                            Text = "Very practical examples."
                        },
                        new
                        {
                            Id = 20,
                            CommenterName = "Sam White",
                            CreatedAt = new DateTime(2024, 1, 26, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            Text = "Docker has been on my learning list, perfect timing!"
                        },
                        new
                        {
                            Id = 21,
                            CommenterName = "Tina Lopez",
                            CreatedAt = new DateTime(2024, 1, 27, 14, 35, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            Text = "Multi-stage builds are a game changer."
                        },
                        new
                        {
                            Id = 22,
                            CommenterName = "Uma Patel",
                            CreatedAt = new DateTime(2024, 1, 28, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            Text = "How do you handle secrets in containers?"
                        },
                        new
                        {
                            Id = 23,
                            CommenterName = "Victor Kim",
                            CreatedAt = new DateTime(2024, 1, 29, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 7,
                            Text = "Great Docker tutorial!"
                        },
                        new
                        {
                            Id = 24,
                            CommenterName = "Wendy Clark",
                            CreatedAt = new DateTime(2024, 3, 6, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 8,
                            Text = "Microservices architecture explained well."
                        },
                        new
                        {
                            Id = 25,
                            CommenterName = "Xavier Rodriguez",
                            CreatedAt = new DateTime(2024, 3, 7, 13, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 8,
                            Text = "What about service discovery?"
                        },
                        new
                        {
                            Id = 26,
                            CommenterName = "Yara Lewis",
                            CreatedAt = new DateTime(2024, 3, 8, 15, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 8,
                            Text = "This helped me design my system."
                        },
                        new
                        {
                            Id = 27,
                            CommenterName = "Zack Walker",
                            CreatedAt = new DateTime(2024, 4, 16, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 9,
                            Text = "Kubernetes is complex but this helps!"
                        },
                        new
                        {
                            Id = 28,
                            CommenterName = "Amy Hall",
                            CreatedAt = new DateTime(2024, 4, 17, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 9,
                            Text = "Deployments and services explained clearly."
                        },
                        new
                        {
                            Id = 29,
                            CommenterName = "Ben Allen",
                            CreatedAt = new DateTime(2024, 4, 18, 14, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 9,
                            Text = "Looking forward to advanced K8s topics."
                        },
                        new
                        {
                            Id = 30,
                            CommenterName = "Cara Young",
                            CreatedAt = new DateTime(2024, 5, 23, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 10,
                            Text = "GitHub Actions workflow examples are great!"
                        },
                        new
                        {
                            Id = 31,
                            CommenterName = "Dan King",
                            CreatedAt = new DateTime(2024, 5, 24, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 10,
                            Text = "How do you handle deployment secrets?"
                        },
                        new
                        {
                            Id = 32,
                            CommenterName = "Eva Wright",
                            CreatedAt = new DateTime(2024, 5, 25, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 10,
                            Text = "Automated my entire pipeline thanks to this!"
                        },
                        new
                        {
                            Id = 33,
                            CommenterName = "Fred Scott",
                            CreatedAt = new DateTime(2024, 5, 26, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 10,
                            Text = "CI/CD made simple."
                        },
                        new
                        {
                            Id = 34,
                            CommenterName = "Gina Green",
                            CreatedAt = new DateTime(2024, 2, 9, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 12,
                            Text = "React hooks changed everything!"
                        },
                        new
                        {
                            Id = 35,
                            CommenterName = "Hank Adams",
                            CreatedAt = new DateTime(2024, 2, 10, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 12,
                            Text = "useState and useEffect explained perfectly."
                        },
                        new
                        {
                            Id = 36,
                            CommenterName = "Iris Baker",
                            CreatedAt = new DateTime(2024, 2, 11, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 12,
                            Text = "Custom hooks tutorial next please!"
                        },
                        new
                        {
                            Id = 37,
                            CommenterName = "Jake Nelson",
                            CreatedAt = new DateTime(2024, 3, 19, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 13,
                            Text = "TypeScript makes JavaScript so much better."
                        },
                        new
                        {
                            Id = 38,
                            CommenterName = "Kate Carter",
                            CreatedAt = new DateTime(2024, 3, 20, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 13,
                            Text = "Type safety is a lifesaver!"
                        },
                        new
                        {
                            Id = 39,
                            CommenterName = "Liam Mitchell",
                            CreatedAt = new DateTime(2024, 3, 21, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            PostId = 13,
                            Text = "Generics explained clearly."
                        },
                        new
                        {
                            Id = 40,
                            CommenterName = "Maya Perez",
                            CreatedAt = new DateTime(2024, 3, 22, 15, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 13,
                            Text = "Switching all my projects to TS now."
                        },
                        new
                        {
                            Id = 41,
                            CommenterName = "Nick Roberts",
                            CreatedAt = new DateTime(2024, 4, 26, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 14,
                            Text = "Redux Toolkit makes state management easier."
                        },
                        new
                        {
                            Id = 42,
                            CommenterName = "Olga Turner",
                            CreatedAt = new DateTime(2024, 4, 27, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 14,
                            Text = "What about Zustand as an alternative?"
                        },
                        new
                        {
                            Id = 43,
                            CommenterName = "Pete Phillips",
                            CreatedAt = new DateTime(2024, 4, 28, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 14,
                            Text = "Great Redux tutorial!"
                        },
                        new
                        {
                            Id = 44,
                            CommenterName = "Rita Campbell",
                            CreatedAt = new DateTime(2024, 5, 31, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            PostId = 15,
                            Text = "Next.js is amazing for full stack apps."
                        },
                        new
                        {
                            Id = 45,
                            CommenterName = "Steve Parker",
                            CreatedAt = new DateTime(2024, 6, 1, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 15,
                            Text = "Server components are the future!"
                        },
                        new
                        {
                            Id = 46,
                            CommenterName = "Tara Evans",
                            CreatedAt = new DateTime(2024, 6, 2, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 15,
                            Text = "SEO benefits are huge."
                        },
                        new
                        {
                            Id = 47,
                            CommenterName = "Umar Edwards",
                            CreatedAt = new DateTime(2024, 6, 3, 15, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 15,
                            Text = "Deploying to Vercel is so easy!"
                        },
                        new
                        {
                            Id = 48,
                            CommenterName = "Vera Collins",
                            CreatedAt = new DateTime(2024, 6, 13, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 16,
                            Text = "CSS Grid is so powerful!"
                        },
                        new
                        {
                            Id = 49,
                            CommenterName = "Will Stewart",
                            CreatedAt = new DateTime(2024, 6, 14, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 16,
                            Text = "Flexbox vs Grid comparison would be great."
                        },
                        new
                        {
                            Id = 50,
                            CommenterName = "Xena Morris",
                            CreatedAt = new DateTime(2024, 6, 15, 14, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 16,
                            Text = "Responsive layouts made easy!"
                        },
                        new
                        {
                            Id = 51,
                            CommenterName = "Yuri Rogers",
                            CreatedAt = new DateTime(2024, 2, 15, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 17,
                            Text = "Pandas is essential for data science."
                        },
                        new
                        {
                            Id = 52,
                            CommenterName = "Zoe Reed",
                            CreatedAt = new DateTime(2024, 2, 16, 13, 35, 0, 0, DateTimeKind.Unspecified),
                            PostId = 17,
                            Text = "DataFrame operations explained well."
                        },
                        new
                        {
                            Id = 53,
                            CommenterName = "Adam Cook",
                            CreatedAt = new DateTime(2024, 2, 17, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 17,
                            Text = "Great intro to Python data science!"
                        },
                        new
                        {
                            Id = 54,
                            CommenterName = "Beth Morgan",
                            CreatedAt = new DateTime(2024, 3, 29, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 18,
                            Text = "TensorFlow tutorial is comprehensive."
                        },
                        new
                        {
                            Id = 55,
                            CommenterName = "Carl Bell",
                            CreatedAt = new DateTime(2024, 3, 30, 12, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 18,
                            Text = "Neural networks finally make sense!"
                        },
                        new
                        {
                            Id = 56,
                            CommenterName = "Dana Murphy",
                            CreatedAt = new DateTime(2024, 3, 31, 14, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 18,
                            Text = "Could you cover CNNs next?"
                        },
                        new
                        {
                            Id = 57,
                            CommenterName = "Eric Bailey",
                            CreatedAt = new DateTime(2024, 4, 1, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 18,
                            Text = "ML is less intimidating now."
                        },
                        new
                        {
                            Id = 58,
                            CommenterName = "Faye Rivera",
                            CreatedAt = new DateTime(2024, 4, 11, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 19,
                            Text = "Query optimization tips are gold!"
                        },
                        new
                        {
                            Id = 59,
                            CommenterName = "Greg Cooper",
                            CreatedAt = new DateTime(2024, 4, 12, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 19,
                            Text = "Indexes explained clearly."
                        },
                        new
                        {
                            Id = 60,
                            CommenterName = "Hope Richardson",
                            CreatedAt = new DateTime(2024, 4, 13, 15, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 19,
                            Text = "My queries are 10x faster now!"
                        },
                        new
                        {
                            Id = 61,
                            CommenterName = "Ian Cox",
                            CreatedAt = new DateTime(2024, 5, 19, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 20,
                            Text = "Great comparison of database types."
                        },
                        new
                        {
                            Id = 62,
                            CommenterName = "Jill Howard",
                            CreatedAt = new DateTime(2024, 5, 20, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 20,
                            Text = "When to use MongoDB vs PostgreSQL?"
                        },
                        new
                        {
                            Id = 63,
                            CommenterName = "Kyle Ward",
                            CreatedAt = new DateTime(2024, 5, 21, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            PostId = 20,
                            Text = "This helped me choose the right DB."
                        },
                        new
                        {
                            Id = 64,
                            CommenterName = "Lynn Torres",
                            CreatedAt = new DateTime(2024, 5, 22, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 20,
                            Text = "Very informative article!"
                        },
                        new
                        {
                            Id = 65,
                            CommenterName = "Mark Peterson",
                            CreatedAt = new DateTime(2024, 3, 9, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 22,
                            Text = "Scrum practices explained well."
                        },
                        new
                        {
                            Id = 66,
                            CommenterName = "Nina Gray",
                            CreatedAt = new DateTime(2024, 3, 10, 13, 35, 0, 0, DateTimeKind.Unspecified),
                            PostId = 22,
                            Text = "Our team adopted these practices!"
                        },
                        new
                        {
                            Id = 67,
                            CommenterName = "Owen Ramirez",
                            CreatedAt = new DateTime(2024, 3, 11, 15, 50, 0, 0, DateTimeKind.Unspecified),
                            PostId = 22,
                            Text = "Agile methodology made simple."
                        },
                        new
                        {
                            Id = 68,
                            CommenterName = "Pam James",
                            CreatedAt = new DateTime(2024, 4, 13, 9, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 23,
                            Text = "Code reviews are so important!"
                        },
                        new
                        {
                            Id = 69,
                            CommenterName = "Quinn Watson",
                            CreatedAt = new DateTime(2024, 4, 14, 12, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 23,
                            Text = "Great tips for constructive feedback."
                        },
                        new
                        {
                            Id = 70,
                            CommenterName = "Ross Brooks",
                            CreatedAt = new DateTime(2024, 4, 15, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 23,
                            Text = "Our code quality improved significantly."
                        },
                        new
                        {
                            Id = 71,
                            CommenterName = "Sara Kelly",
                            CreatedAt = new DateTime(2024, 4, 16, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 23,
                            Text = "Every developer should read this."
                        },
                        new
                        {
                            Id = 72,
                            CommenterName = "Tony Sanders",
                            CreatedAt = new DateTime(2024, 5, 21, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            PostId = 24,
                            Text = "Technical debt is real!"
                        },
                        new
                        {
                            Id = 73,
                            CommenterName = "Uma Price",
                            CreatedAt = new DateTime(2024, 5, 22, 13, 25, 0, 0, DateTimeKind.Unspecified),
                            PostId = 24,
                            Text = "Balancing features and refactoring is hard."
                        },
                        new
                        {
                            Id = 74,
                            CommenterName = "Vince Bennett",
                            CreatedAt = new DateTime(2024, 5, 23, 15, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 24,
                            Text = "Practical advice for managing debt."
                        },
                        new
                        {
                            Id = 75,
                            CommenterName = "Wanda Wood",
                            CreatedAt = new DateTime(2024, 6, 9, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PostId = 25,
                            Text = "Leadership skills are crucial!"
                        },
                        new
                        {
                            Id = 76,
                            CommenterName = "Xavier Barnes",
                            CreatedAt = new DateTime(2024, 6, 10, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            PostId = 25,
                            Text = "Transitioning to tech lead soon, this helps!"
                        },
                        new
                        {
                            Id = 77,
                            CommenterName = "Yolanda Ross",
                            CreatedAt = new DateTime(2024, 6, 11, 14, 40, 0, 0, DateTimeKind.Unspecified),
                            PostId = 25,
                            Text = "Great insights on team leadership."
                        },
                        new
                        {
                            Id = 78,
                            CommenterName = "Zane Henderson",
                            CreatedAt = new DateTime(2024, 6, 12, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            PostId = 25,
                            Text = "Every tech lead should read this."
                        });
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "A comprehensive guide to building modern web applications...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Getting Started with ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Content = "Deep dive into EF Core relationships and migrations...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding Entity Framework"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Content = "Learn how to design clean and maintainable APIs...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "REST API Best Practices"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Content = "Master async/await patterns for better performance...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Async Programming in C#"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Content = "Understanding DI containers and service lifetimes...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dependency Injection Explained"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Content = "Work in progress on complex query patterns...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Advanced LINQ Queries"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Content = "Containerize your applications with Docker...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Docker for .NET Developers"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Content = "Building scalable distributed systems...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Microservices Architecture"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            Content = "Orchestrating containers in production...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kubernetes Basics"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Content = "Automating your deployment pipeline...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CI/CD with GitHub Actions"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Content = "Exploring Istio and service mesh...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Service Mesh Patterns"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Content = "Modern React development with hooks...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "React Hooks Tutorial"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Content = "Adding type safety to your JavaScript...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "TypeScript for Beginners"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Content = "Managing complex application state...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "State Management with Redux"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Content = "Building modern web apps with Next.js...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Next.js Full Stack Apps"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Content = "Modern layout techniques for responsive design...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CSS Grid and Flexbox"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Content = "Getting started with pandas and numpy...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python Data Science Basics"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Content = "Building neural networks from scratch...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning with TensorFlow"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Content = "Writing efficient database queries...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Query Optimization"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 4,
                            Content = "Choosing the right database for your needs...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NoSQL vs SQL Databases"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 4,
                            Content = "Working with Apache Spark...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Big Data Processing"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 5,
                            Content = "Implementing Scrum in your team...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Agile Development Practices"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 5,
                            Content = "Improving code quality through reviews...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Code Review Best Practices"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 5,
                            Content = "Balancing features and maintainability...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Technical Debt Management"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            Content = "Growing from developer to tech lead...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Leadership Skills"
                        });
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Comment", b =>
                {
                    b.HasOne("BlogPlatformApi.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.HasOne("BlogPlatformApi.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
