// <auto-generated />
using System;
using BlogPlatformApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPlatformApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260805135646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BlogPlatformApi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("JoineDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sarah.j@example.com",
                            FullName = "Sarah Johnson",
                            JoineDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Email = "m.chen@example.com",
                            FullName = "Michael Chen",
                            JoineDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Email = "emma.w@example.com",
                            FullName = "Emma Williams",
                            JoineDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.m@example.com",
                            FullName = "David Martinez",
                            JoineDate = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "lisa.a@example.com",
                            FullName = "Lisa Anderson",
                            JoineDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommenterName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "A comprehensive guide to building modern web applications...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Getting Started with ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Content = "Deep dive into EF Core relationships and migrations...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding Entity Framework"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Content = "Learn how to design clean and maintainable APIs...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "REST API Best Practices"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Content = "Master async/await patterns for better performance...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Async Programming in C#"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Content = "Understanding DI containers and service lifetimes...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dependency Injection Explained"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Content = "Work in progress on complex query patterns...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Advanced LINQ Queries"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            Content = "Containerize your applications with Docker...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Docker for .NET Developers"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Content = "Building scalable distributed systems...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Microservices Architecture"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            Content = "Orchestrating containers in production...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kubernetes Basics"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 2,
                            Content = "Automating your deployment pipeline...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CI/CD with GitHub Actions"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 2,
                            Content = "Exploring Istio and service mesh...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Service Mesh Patterns"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Content = "Modern React development with hooks...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "React Hooks Tutorial"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            Content = "Adding type safety to your JavaScript...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "TypeScript for Beginners"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 3,
                            Content = "Managing complex application state...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "State Management with Redux"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            Content = "Building modern web apps with Next.js...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Next.js Full Stack Apps"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 3,
                            Content = "Modern layout techniques for responsive design...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "CSS Grid and Flexbox"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Content = "Getting started with pandas and numpy...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Python Data Science Basics"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Content = "Building neural networks from scratch...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Machine Learning with TensorFlow"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Content = "Writing efficient database queries...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Query Optimization"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 4,
                            Content = "Choosing the right database for your needs...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "NoSQL vs SQL Databases"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 4,
                            Content = "Working with Apache Spark...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = false,
                            PublishedDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Draft: Big Data Processing"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 5,
                            Content = "Implementing Scrum in your team...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Agile Development Practices"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 5,
                            Content = "Improving code quality through reviews...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Code Review Best Practices"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 5,
                            Content = "Balancing features and maintainability...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Technical Debt Management"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 5,
                            Content = "Growing from developer to tech lead...",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPublished = true,
                            PublishedDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Team Leadership Skills"
                        });
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Comment", b =>
                {
                    b.HasOne("BlogPlatformApi.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.HasOne("BlogPlatformApi.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("BlogPlatformApi.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
